In [4]:
import pandas as pd
#import seaborn as sns
#import matplotlib.pyplot as plt
import sklearn as sk
import numpy as np

import lightgbm

In [5]:
xtrain=pd.read_csv("data/xtrain_challenge.csv")
ytrain=pd.read_csv("data/ytrain_challenge.csv")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [6]:
xtrain.head(10)

,qs1,qs2,qs3,qs4,qs5,qs6,qs7,qs8,qs9,qs10,qs11,qs12,qs13,qr1,qr2,qr3,qr4,qr5,qr6,qr7,qr8,qr9,qr10,qr11,qr12,qr13,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11
0,1.0,0.0,0.0,-6.24,-5.27,-1.86,0.63,3.27,0.89,350.98,64.86,0.0,1.00,1.0,0.0,0.0,-9.44,-12.53,0.84,2.59,1.53,1.03,276.02,58.02,0.0,1.00,2405.94,1981.09,2677.84,2470.44,1579.39,2185.79,2118.77,2580.99,2498.04,3180.58,2718.29
1,1.0,0.0,0.0,-0.42,-4.50,-4.31,1.61,1.72,2.76,347.06,28.85,0.0,0.99,1.0,0.0,0.0,-0.35,-18.97,-1.31,1.23,0.84,0.34,263.84,30.50,0.0,1.00,3241.37,2015.24,3987.19,3343.53,2894.69,2947.34,2689.42,3763.51,2544.22,3515.58,3247.49
2,1.0,0.0,0.0,33.76,-19.29,2.71,1.73,1.32,1.53,135.94,57.65,1.0,0.01,1.0,0.0,0.0,-12.58,-9.99,-0.15,1.21,0.34,1.60,357.67,51.98,1.0,1.00,2199.22,2549.59,2164.41,2100.69,1294.35,2136.04,1644.05,2308.05,1774.88,3005.79,2507.02
3,1.0,0.0,0.0,-2.82,-8.04,3.04,0.94,2.92,0.09,288.07,21.23,0.0,0.94,1.0,0.0,0.0,1.57,-13.22,-2.66,1.18,0.23,0.38,268.44,24.59,0.0,0.19,2390.40,2141.75,2086.02,2154.69,1247.48,1903.36,2232.54,2146.34,2201.53,3315.03,2274.76
4,1.0,0.0,0.0,3.56,-10.61,-0.65,0.19,1.04,2.10,166.12,37.36,1.0,0.00,1.0,0.0,0.0,20.03,-15.53,-1.21,1.31,0.23,1.25,172.19,26.14,0.0,1.00,1822.14,2202.60,2150.07,2194.25,1575.43,2345.59,1976.82,1440.78,2061.06,2927.96,2073.16
5,1.0,0.0,0.0,3.10,-6.27,-2.70,0.20,1.82,1.16,267.62,34.40,0.0,1.00,1.0,0.0,0.0,-10.03,3.83,-1.81,2.62,0.31,0.08,264.94,35.82,0.0,1.00,1654.88,1759.45,2727.66,2253.47,2091.18,2021.04,1963.33,2436.20,2333.33,3034.30,2359.34
6,1.0,0.0,0.0,-5.08,3.91,-0.47,1.45,0.07,2.15,188.00,36.80,0.0,1.00,1.0,0.0,0.0,0.02,1.34,-2.72,1.80,0.12,0.65,231.98,37.27,0.0,0.00,2320.56,1685.26,2307.06,1939.64,1549.16,2148.36,1590.07,2107.89,2273.71,3169.00,2403.95
7,1.0,0.0,0.0,1.52,-6.21,1.53,0.91,0.77,0.65,306.03,32.23,0.0,1.00,1.0,0.0,0.0,0.53,1.49,1.30,0.57,0.18,1.07,404.22,24.13,0.0,1.00,2210.33,1968.06,2738.41,2524.63,2313.01,2096.95,2466.05,2148.19,2413.82,3231.56,2895.45
8,1.0,0.0,0.0,-0.51,9.75,8.86,1.49,0.31,1.29,375.26,43.40,0.0,1.00,1.0,0.0,0.0,2.91,9.49,-8.28,2.17,1.02,0.07,344.02,46.38,0.0,1.00,2180.16,2385.96,2246.63,2169.35,1783.36,1934.03,2355.90,2034.93,2133.04,3286.98,2282.92
9,1.0,0.0,0.0,-7.89,-5.71,-12.80,2.28,0.40,1.50,282.73,40.00,0.0,0.00,1.0,0.0,0.0,11.33,-1.36,5.89,3.80,0.32,0.79,263.39,26.94,0.0,0.00,5428.98,4299.10,6658.78,8224.55,6603.65,6599.55,7133.70,6894.58,7169.84,6608.53,6802.31

In [7]:
ytrain.head(10)

   y
0  0
1  0
2  0
3  0
4  0
5  0
6  0
7  0
8  0
9  1

In [8]:
# Prenons juste les valeurs S1 à S11
cols_S1_11 = list(xtrain.columns)[26:]

In [9]:
X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(xtrain, ytrain, test_size=0.33, random_state=42)

In [ ]:
X_train_s = X_train[cols_S1_11]/10000.

In [ ]:
X_train_s.head(10)

In [ ]:
 # making lgbm datasets for train and valid
d_train = lightgbm.Dataset(X_train, y_train)
d_valid = lightgbm.Dataset(X_test, y_test)
    
parameters = {
    'application': 'binary',
    'objective': 'binary',
    'metric': 'binary_error',
    'is_unbalance': 'false',
    'boosting': 'gbdt',
    'num_leaves': 100,
    'feature_fraction': 0.6,
    'bagging_fraction': 0.8,
    'bagging_freq': 20,
    'learning_rate': 0.04,
    'verbose': 0
}

model = lightgbm.train(parameters,
                       d_train,
                       valid_sets=d_valid,
                       num_boost_round=5000,
                       early_stopping_rounds=150)   
    # making prediciton for one column

In [ ]:

soft = model.predict(X_test)

print('Fininshed Training')
soft

In [ ]:

yvalid = soft

In [ ]:
N = np.sum(y_test == 0).values
P = np.sum(y_test == 1).values

In [ ]:

yvalid_scoreordered = y_test.values[np.argsort(yvalid)]


FP = 0.0
TP = 0.0
val = 0
print(N)
print(P)
for i in range(len(y_test) - 1, -1, -1):        
    if (yvalid_scoreordered[i] == 1):
        TP = TP + 1
    else:
        FP = FP + 1
        #print(X_test[cols].iloc(i))
    if (FP / N > 10**-4):
        FP = FP - 1
        break
print("For the smallest FPR <= 10^-4 (i.e., ", FP / N, ") TPR = ", TP / P, ".", sep = "")

In [ ]:
# Load test data
xtest = pd.read_csv('data/xtest_challenge.csv')

In [ ]:
# Classify the provided test data
ytest = model.predict(xtest[cols_S1_11].values)
print(ytest.shape)
np.savetxt('ytest_lbgm.csv', ytest, fmt = '%1.15f', delimiter=',')

In [ ]:


model.save_model('lgbm.txt')